apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: k7fbkl7t0-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/k7fbkl7t0-java-quarkus-gitops